import path from "node:path";
import type { BrainConfig } from "./config.js";

export function brainPaths(root: string) {
  const r = path.resolve(root);
  return {
    root: r,
    raw: path.join(r, "raw"),
    wiki: path.join(r, "wiki"),
    outputs: path.join(r, "outputs"),
    videos: path.join(r, "videos"),
    assets: path.join(r, "assets"),
    brain: path.join(r, ".brain"),
    claudeMd: path.join(r, "CLAUDE.md"),
    readme: path.join(r, "README.md"),
    logMd: path.join(r, "log.md"),
    envFile: path.join(r, ".env"),
    stateJson: path.join(r, ".brain", "state.json"),
    fileHashesJson: path.join(r, ".brain", "file-hashes.json"),
    ingestCacheJson: path.join(r, ".brain", "ingest-cache.json"),
    graphJson: path.join(r, ".brain", "graph.json"),
    searchIndexJson: path.join(r, ".brain", "search-index.json"),
    runsDir: path.join(r, ".brain", "runs"),
    promptsDir: path.join(r, ".brain", "prompts"),
    templatesDir: path.join(r, ".brain", "templates"),
    reviewStateJson: path.join(r, ".brain", "review-state.json"),
    lastDoctorJson: path.join(r, ".brain", "last-doctor.json"),
    traceDir: path.join(r, ".brain", "trace"),
    promotionInboxJson: path.join(r, ".brain", "promotion-inbox.json"),
    decisionLedgerJson: path.join(r, ".brain", "decision-ledger.json"),
    lineageDir: path.join(r, ".brain", "lineage"),
    proposedWikiUpdatesDir: path.join(r, ".brain", "proposed-wiki-updates"),
    decisionsWikiDir: path.join(r, "wiki", "decisions"),
    unsupportedClaimsJson: path.join(r, ".brain", "unsupported-claims.json"),
    conflictsJson: path.join(r, ".brain", "conflicts.json"),
    pageQualityJson: path.join(r, ".brain", "page-quality.json"),
    sourceLineageJson: path.join(r, ".brain", "source-lineage.json"),
    knowledgeDriftJson: path.join(r, ".brain", "knowledge-drift.json"),
    openLoopsJson: path.join(r, ".brain", "open-loops.json"),
    reviewPriorityJson: path.join(r, ".brain", "review-priority.json"),
    synthesisHeatmapJson: path.join(r, ".brain", "synthesis-heatmap.json"),
    executiveSnapshotJson: path.join(r, ".brain", "executive-snapshot.json"),
    canonPromotionsJson: path.join(r, ".brain", "canon-promotions.json"),
    reviewSlaJson: path.join(r, ".brain", "review-sla.json"),
    decisionImpactJson: path.join(r, ".brain", "decision-impact.json"),
    evidenceBaselineJson: path.join(r, ".brain", "evidence-baseline.json"),
    evidenceChangeAlertsJson: path.join(r, ".brain", "evidence-change-alerts.json"),
    snapshotBundlesJson: path.join(r, ".brain", "snapshot-bundles.json"),
    resolutionQualityJson: path.join(r, ".brain", "resolution-quality.json"),
    canonDriftWatchlistJson: path.join(r, ".brain", "canon-drift-watchlist.json"),
    reviewSessionStateJson: path.join(r, ".brain", "review-session-state.json"),
    reviewsDir: path.join(r, "outputs", "reviews"),
    pageSnapshotsDir: path.join(r, "outputs", "reviews", "snapshots"),
    relationshipHubMd: path.join(r, "wiki", "relationship-hub.md"),
    canonicalBoardJson: path.join(r, ".brain", "canonical-board.json"),
    resolutionsJson: path.join(r, ".brain", "resolutions.json"),
    evidenceDensityJson: path.join(r, ".brain", "evidence-density.json"),
    driftDecisionLinksJson: path.join(r, ".brain", "drift-decision-links.json"),
    humanReviewJson: path.join(r, ".brain", "human-review.json"),
    sourceSupersessionJson: path.join(r, ".brain", "source-supersession.json"),
    crossSignalCorrelationJson: path.join(r, ".brain", "cross-signal-correlation.json"),
    reviewDebtJson: path.join(r, ".brain", "review-debt.json"),
    decisionSunsetJson: path.join(r, ".brain", "decision-sunset.json"),
    strategicThemesJson: path.join(r, ".brain", "strategic-themes.json"),
    confidenceHistoryJson: path.join(r, ".brain", "confidence-history.json"),
    humanOverridesJson: path.join(r, ".brain", "human-overrides.json"),
    canonAdmissionJson: path.join(r, ".brain", "canon-admission.json"),
    canonCouncilJson: path.join(r, ".brain", "canon-council.json"),
    governanceSettingsJson: path.join(r, ".brain", "governance-settings.json"),
    governanceActionLogJson: path.join(r, ".brain", "governance-action-log.json"),
    councilMinutesLogMd: path.join(r, "outputs", "reviews", "canon-council-minutes-log.md"),
    lastCanonGuardJson: path.join(r, ".brain", "last-canon-guard.json"),
    canonFragilityJson: path.join(r, ".brain", "canon-fragility.json"),
    executiveTrustSummaryJson: path.join(r, ".brain", "executive-trust-summary.json"),
    indexMd: path.join(r, "wiki", "INDEX.md"),
    dashboardMd: path.join(r, "wiki", "dashboard.md"),
    dailyVideosMd: path.join(r, "videos", "daily_videos.md"),
  };
}

export type BrainPaths = ReturnType<typeof brainPaths>;

export function wikiPagePath(
  cfg: BrainConfig,
  domainFolder: string,
  slug: string
): string {
  return path.join(cfg.root, "wiki", domainFolder, `${slug}.md`);
}
